###user###
CREATE TABLE `user`(
uuid VARCHAR(48) NOT NULL,
username VARCHAR(64) NOT NULL,
`password` VARCHAR(64) NOT NULL,
phone VARCHAR(22) NOT NULL,
gender VARCHAR(4) NOT NULL,
img VARCHAR(256) DEFAULT "https://pasd-1259423553.cos.ap-beijing.myqcloud.com/default.jpg",
deleted TINYINT NOT NULL DEFAULT 0,
create_time DATETIME NOT NULL,
update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
INDEX idx_uuid(uuid) USING BTREE
)ENGINE = INNODB AUTO_INCREMENT = 2048 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = COMPACT;

###msg####
CREATE TABLE `msg`(
uuid VARCHAR(48) NOT NULL,
user_uuid VARCHAR(48) NOT NULL,
img_url VARCHAR(1024),
`describe` VARCHAR(512) NOT NULL,
deleted TINYINT NOT NULL DEFAULT 0,
create_time DATETIME NOT NULL,
update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
INDEX idx_uuid(uuid) USING BTREE,
INDEX idx_user_uuid(user_uuid) USING BTREE
)ENGINE = INNODB AUTO_INCREMENT = 2048 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = COMPACT;

###like###
CREATE TABLE `like`(
uuid VARCHAR(48) NOT NULL,
user_uuid VARCHAR(48) NOT NULL,
msg_uuid VARCHAR(48) NOT NULL,
deleted TINYINT NOT NULL DEFAULT 0,
create_time DATETIME NOT NULL,
update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
INDEX idx_uuid(uuid) USING BTREE,
INDEX idx_user_msg_uuid(user_uuid, msg_uuid) USING BTREE
)ENGINE = INNODB AUTO_INCREMENT = 2048 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = COMPACT;

###comment###
CREATE TABLE `comment`(
uuid VARCHAR(48) NOT NULL,
user_uuid VARCHAR(48) NOT NULL,
msg_uuid VARCHAR(48) NOT NULL,
content VARCHAR(256) NOT NULL,
deleted TINYINT NOT NULL DEFAULT 0,
create_time DATETIME NOT NULL,
update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
INDEX idx_uuid(uuid) USING BTREE,
INDEX idx_user_msg_uuid(user_uuid, msg_uuid) USING BTREE
)ENGINE = INNODB AUTO_INCREMENT = 2048 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = COMPACT;

ALTER TABLE `user` ADD mail VARCHAR(64) NOT NULL;
ALTER TABLE `user` ADD age INT DEFAULT 0;